version: '3'

services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./conf:/config
      - ./gdrive/series:/data/tvshows
      - ./gdrive/pelis:/data/movies
      - ./gdrive/podcast:/data/podcast
      - ./gdrive/iptv:/data/iptv
      - ./gdrive/record:/data/record
    expose:
      - 8096
    network_mode: "host"
    depends_on:
      - rclone-mount

  rclone-mount:
    image: pablokbs/rclone-mount
    restart: unless-stopped
    ports:
      - '81:80'
    cap_add:
      - SYS_ADMIN
    security_opt:
      - 'apparmor:unconfined'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - './conf/rclone:/config'
      - './gdrive:/mnt/mediaefs:shared'
    logging:
      options:
        max-size: 1g
    container_name: rclone-mount
    devices:
      - /dev/fuse
    environment:
      - 'RemotePath=gdrive:'
      - 'MountCommands=--allow-other --allow-non-empty --buffer-size 256M'
      - 'ConfigName=rclone.conf'

